### ISSUE TITLE
Nova validação de telefone

### ISSUE THREAD

**Issue by jonathangoncalves** [gammasoft/brasil#13]
Olá eu criei uma validação de telefone que inclui várias coisas. Queria que vocês considerassem minha validação no código de vocês!

https://gist.github.com/jonathangoncalves/7bdec924e9bd2bdf353d6b7520820b62

Obrigado.

**Comment by renatoargh** [comment]
Bom dia @jonathangoncalves obrigado por enviar o seu código! Dele vou incorporar apenas a validação dos casos triviais no brasil, que realmente está faltando.

Eu tenho medo de colocar uma validação muito restritiva e dar muitos falsos inválidos impedindo o usuário de informar o número correto. Podemos assumir que se o usuário quiser informar um número errado ele sempre vai conseguir. A melhor validação, quando o telefone é indispensável é aquela por SMS. Se você quiser propor alguma alteração no brasil é só mandar um PR. Valeu, abraço!

**Comment by jonathangoncalves** [comment]
De fato!

A validação está bem restritiva no meu caso pois onde estou utilizando foi
solicitado que seja validado o máximo possível.

O bom do código que fiz que quem quiser utilizar qualquer nível de
validação, vai ser fácil! Tinha mais coisas para colocar mas como você
disse, restringir demais é ruim.

Sobre SMS a validação é bem criteriosa em questão de celulares pois
verifica a questão do 9 digito e se o número é válido.

De qualquer forma fico feliz de apreciarem meu código!

Em sex, 3 de jun de 2016 19:11, Renato Gama <notifications@github.com>
escreveu:

> Bom dia @jonathangoncalves <https://github.com/jonathangoncalves>
> obrigado por enviar o seu código! Dele vou incorporar apenas a validação
> dos casos triviais no brasil, que realmente está faltando.
>
> Eu tenho medo de colocar uma validação muito restritiva e dar muitos
> falsos inválidos impedindo o usuário de informar o número correto. Podemos
> assumir que se o usuário quiser informar um número errado ele sempre vai
> conseguir. A melhor validação, quando o telefone é indispensável é aquela
> por SMS. Se você quiser propor alguma alteração no brasil é só mandar um
> PR. Valeu, abraço!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gammasoft/brasil/issues/13#issuecomment-223706985>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD7XgORUIwm-7OmLhuUCR4TOovkoZlgtks5qIKaTgaJpZM4ItqgE>
> .
>
-- 

Atenciosamente,

Jonathan Gonçalves

**Comment by jonathangoncalves** [comment]
Olá, gammasoft/brasil.

Gostaria que você fizesse parte da minha rede do LinkedIn para compartilhar atualizações e manter contato.

- Jonathan

Confirme que você conhece Jonathan: https://www.linkedin.com/e/v2?e=0-ir1xdboq-4k&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=rYBBfQcj&invitationId=6163297133073092609








Você recebeu um convite de conexão. O LinkedIn utiliza seu endereço de e-mail para fazer sugestões a nossos usuários em recursos como Pessoas que talvez você conheça. Clique aqui para cancelar a inscrição: https://www.linkedin.com/e/v2?e=0-ir1xdboq-4k&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHlxkHbDPIpzwAAAVYhvBptFkgYp9pjGSVYHc-fWsM_W4oOEjA3u0fLJ4kckPZqptUozGkkzNV_dS7MNcwYLN-0p8tQ597L7XHSdOzU4_8xe3E0mEiLPHXVXVT2SXu4dNm9tjeQk556xKfRrqZWVSTmUNxFzhrwd00-y7bjb4SsaJyrTEUChefJ9eX4q6x7yQyX&eid=0-ir1xdboq-4k


Este e-mail foi enviado para reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ir1xdboq-4k&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jonathangoncalves** [comment]
Jonathan Gonçalves would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-pwiy9g-irc9lvlg-rn&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=rYBBfQcj&invitationId=6163297133073092609

View Jonathan Gonçalves&#39;s profile: https://www.linkedin.com/e/v2?e=-pwiy9g-irc9lvlg-rn&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=rYBBfQcj&invitationId=6163297133073092609

Gostaria de adicionar você à minha rede profissional no LinkedIn.





Você recebeu um convite para se conectar. O LinkedIn utiliza seu endereço de e-mail para fazer sugestões a nossos usuários em recursos como Pessoas que talvez você conheça. Cancelar inscrição: https://www.linkedin.com/e/v2?e=-pwiy9g-irc9lvlg-rn&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-pwiy9g-irc9lvlg-rn&loid=AQG0i6uJlFvjlgAAAVZH7dihZejBw705wSyMcVpn7ryV7WIC0V7eiOE5bXVaeZdQf502PbCqSWQdkXyFAvyJv1FwrHUc25p7x1AWWSm3Tg8PIpjToDchA7S1p3XI8jySxuY-g_aCA3PB1j6Zs5N1SxfBhRk1Ep7Dzi-n-dBy-ZL7YYW4yaYKR2CuBwwwmL7xxS5H

Este e-mail foi enviado para reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-pwiy9g-irc9lvlg-rn&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043. LinkedIn e a logomarca do LinkedIn são marcas registradas da LinkedIn.
