### ISSUE TITLE
Validador de CNPJ/CPF não deve aceitar valores triviais

### ISSUE THREAD

**Issue by renatoargh** [gammasoft/brasil#8]
O validador atualmente aceita valores como 00000000 ou 111111111 ou 2222222

**Comment by rodrigorizando** [comment]
Caros,

Eu fiz a parte de consulta na Receita Federal PF, mas.. é preciso fazer os
testes e arrumar um bug do jquery no IE, interessa vcs? para quem posso
enviar? n quero nem comitar...

att,
rodrigo
rodrigorizando.com

Em 18 de fevereiro de 2015 17:38, Renato Gama <notifications@github.com>
escreveu:

**Comment by renatoargh** [comment]
Rodrigo, comita sim, manda o pull request sem medo de ser feliz! Abraço
