### ISSUE TITLE
Erro na Consulta de CNPJ

### ISSUE THREAD

**Issue by valtlfelipe** [gammasoft/brasil#9]
Caros,

Está retornando um erro na consulta do CNPJ na hora de trazer o captcha do site. Inclusive na própria demo de vocês ([http://brasil.gammasoft.com.br/](http://brasil.gammasoft.com.br/)) ocorre o mesmo erro que em minha aplicação: 

```javascript
Error: Impossível encontrar o valor do sessionId, do viewState ou do captchaUrl
   at IncomingMessage.<anonymous> (/home/ec2-user/brasil-exemplo/node_modules/brasil/lib/consultas/consultaCnpj.js:192:37)
   at IncomingMessage.EventEmitter.emit (events.js:117:20)
   at _stream_readable.js:920:16
   at process._tickCallback (node.js:415:13)
```

**Comment by renatoargh** [comment]
@valtlfelipe a receita alterou recentemente o HTML retornado deste serviço (*inclusive agora ela inclui mais dados sobre o CNPJ, o que é ótimo!*) mas isso quebrou o mecanismo atual. Em breve vou consertar e subir a versão mas não tenho previsão de quando. Se você tiver interesse fala comigo no gitter que posso te dar as dicas de como consertar (caso você não possa esperar o patch)

**Comment by perciag** [comment]
Olá tenho interesse nessa ferramenta tb, como posso ajudar na correção?

**Comment by TheEld** [comment]
@renatoargh, tenho interesse em ajudar, como poderiamos pegar as dicas pra colaborar na correção?

**Comment by renatoargh** [comment]
@perciag e @TheEld no arquivo [consultaCnpj.js](https://github.com/gammasoft/brasil/blob/master/lib/consultas/consultaCnpj.js) na função `executarParseDoHtml`. O HTML do site da receita mudou recentemente e essa função precisa se adequar ao novo layout. Sim, eu sei que o código esta meio caótico, mas acho que rola de corrigir sim.

**Comment by renatoargh** [comment]
@perciag  e @TheEld Vou dar uma analisada no problema e já retorno uma posição para vocês.

**Comment by TheEld** [comment]
Olá Renato,


Pelo que olhei, acho que seja um problema na função *obterUrlDoCaptcha(), *mas
posso estar equivocado. Obrigado pela atenção!



2015-07-16 12:23 GMT-03:00 Renato Gama <notifications@github.com>:

**Comment by renatoargh** [comment]
Estou vendo este issue agora, em meia hora ou um pouco mais te retorno uma posição, como estou com tempo hoje acho que eu posso resolver caso o problema seja simples! Valeu

**Comment by renatoargh** [comment]
@TheEld corrigi alguns problemas. Na verdade a receita mudou o mecanismo de busca, mas acabou reduzindo a complexidade do código. Agora o que ta pegando é que todos os captchas ele retorna como "Captcha errado". Não sei porque. Da uma olhada no [codigo que eu acabei de comitar](https://github.com/gammasoft/brasil/blob/master/lib/consultas/consultaCnpj.js), caso voce tenha alguma ideia me avisa! O problema esta na função `obterDados`.

Para testar;
```javascript
var brasil = require('brasil');

// Comenta o de baixo e rode primeiro este trecho para obter o captcha:
brasil.consultas.cnpj.obterCaptcha(function(err, captcha) {
    if(err) {
        throw err;
    }

    console.log(JSON.stringify(captcha, null, 4));
});

// Comente o de cima e depois rode esse aqui:
brasil.consultas.cnpj.obterDados('00132781000178', {
    sessionId: 'o session id que vc obtiver da primeira execucao',
    solucao: 'a solucao do captcha'
}, function(err, resultado) {
    if(err) {
        throw err;
    }

    console.log(JSON.stringify(resultado, null, 4));
});
```

**Comment by TheEld** [comment]
@renatoargh Certo, vou atualizar e investigar o mais breve possível, obrigado novamente pela prontidão.

**Comment by valtlfelipe** [comment]
@renatoargh eu testei aqui o seu commit, e está funcionando perfeitamente! Em todas as vezes que testei aqui retornou os dados corretos do CNPJ. Talvez a receita tenha alterado novamente algo no site de Julho para cá, que fez com que a sua correção funcione agora.

Se alguém mais puder testar e deixar um feedback aqui seria legal.

**Comment by renatoargh** [comment]
@valtlfelipe na verdade eu subi [dois](https://github.com/gammasoft/brasil/commit/3ca47e7f302af9a3bff3a4d153068a1627a7d9b0) [commits](https://github.com/gammasoft/brasil/commit/c3397817ac178922ea3b23807156d51ef3e9f793) em julho que acho que ajudaram a resolver o problema. Como você testou e eu também testei e esta funcionando vou fechar o issue, qualquer coisa da um toque aqui novamente por favor!

**Comment by valtlfelipe** [comment]
Show! Muito obrigado pela correção!
